export default function Topbar() {
  return (
    <div
      className="
        flex
        items-center
        justify-between
        mb-10
      "
    >
      <div>
        <p
          className="
            text-cyan-400
            uppercase
            tracking-[0.3em]
            text-sm
            mb-3
          "
        >
          Enterprise Dashboard
        </p>

        <h1
          className="
            text-6xl
            font-black
            bg-gradient-to-r
            from-cyan-400
            to-blue-500
            text-transparent
            bg-clip-text
          "
        >
          Payroll Insights
        </h1>
      </div>

      <div
        className="
          flex
          items-center
          gap-4
        "
      >
        <input
          placeholder="Search..."
          className="
            bg-white/5
            border
            border-white/10
            rounded-2xl
            px-5
            py-3
            outline-none
            backdrop-blur
            text-white
            w-64
          "
        />

        <div
          className="
            px-4
            py-2
            rounded-full
            bg-green-500/20
            text-green-400
            border
            border-green-400/20
          "
        >
          Online
        </div>

        <div
          className="
            w-12
            h-12
            rounded-full
            bg-gradient-to-br
            from-cyan-400
            to-blue-600
            shadow-lg
            shadow-cyan-500/30
          "
        />
      </div>
    </div>
  );
}
