version: '3.9'

services:
  postgres:
    image: postgres:16

    container_name: workhours-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workhours

    ports:
      - "5432:5432"